const purple = '#292477'
const gray = '#757575'
const white = '#EFF1ED'
const red = '#b71845'
const orange = '#85380e'
const blue = '#4e4cb8'
const lightPurp = '#7c53c3'
const pink = '#b93fb3'
const black = '#000'
export const primary = orange
export const secondary = gray
export const textPrimary = white
export const textSecondary = black
export const viewBackground = white
export const deckRowBackground = '#fff'
